# Configuração para o Firebase Web SDK (usado pelo Pyrebase)
[firebase]
apiKey = "AIzaSyB5chTFihZM_v-5bkVecmDDUvkOKG7C22Q"  # Substitua pela sua Web API Key real
authDomain = "lgpd-ipem-mg-9f1a5.firebaseapp.com"    # Substitua pelo seu Auth Domain real
projectId = "lgpd-ipem-mg-9f1a5"     # Substitua pelo seu Project ID real
storageBucket = "lgpd-ipem-mg-9f1a5.appspot.com" # Substitua pelo seu Storage Bucket real
messagingSenderId = "510388427771" # Substitua pelo seu Messaging Sender ID real
appId = "1:510388427771:web:fdcda6526f125892db8266"           # Substitua pelo seu App ID real
databaseURL = ""                                  # URL do Realtime Database (opcional, deixe "" se não usar)

# Credenciais para o Firebase Admin SDK (Service Account JSON)
[FIREBASE_CREDENTIALS]
type = "service_account"
project_id = "lgpd-ipem-mg-9f1a5"
private_key_id = "4d6f440ff179ae46efdaf36afd5da673d0485b2a" # Substitua pelo seu private_key_id real
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCrh38trcLOaKgY
7Gni4+yb+0kUuQK/qLp2ghEETD7zvMvIvOKF1puRQ9YCtGX3uPQRAeuBS3o138Jd
qmsJW/WJlvcglaKWd22TsRA/yu3968BINveS7GUxWqjyWbnMKuGV8JSaQjDrg1Xk
KymowUf/gdj0RFS8HzfnIl1+5MoPEF8qv3czBIEaqKoqKmdhGVRzFYHmEjq1GAB1
A1OgWkCl+GYb/XDknmjq0+CfSRcGxwtveaHlAu7JCSxXbfuPuCr/E5He+75F2BF7
P8oXN8HcClhyDwurcNHf6nuRqA+Vls7rEjWr19G1aKUjs7MulesJ2GpH7B/JNIik
w3ymisCLAgMBAAECggEASgevxwowgp8+tYsLZCZUzzlT4EK9QfTTjSQzrfQuU0nP
dfK3nWXzPG3XptEvFQxZIiH+/42Q0EGjhINxsNdkkJ58SC7svh4LR+vqhG3T63xd
P42hqmKmhfeH5Rj+jHSRagIsUKtyq6LCZjiOwUuyBD+JYFtBavPaT8JQMd0SrA8C
5tYb2cgIEYTciE+GUut/tESc4R9tSxbMd5BD0lXceiGlgeOnQIyxpjZlZhIe+1cw
WwmasrWhbt+Ufi+PjN9zLOI7dwNjKfeDCGbTQIbmRO/pCCmOOQk+bD+/qA5SY3zY
n0511x8c4a/v3s5T+Y6qC0WUSuFkGVAVFsLSGj27eQKBgQDWNaDW12MKgQxGE9cq
1iJ8ZRs/pDCaoEP41sClKPVWKXgtm+ju0obVOUXUFFp990hyi+rJmWWgI/yCvLEo
r2wW2dO/65EkD0VwYKfMNrxY3j49iYI7uYas5wWthgjfJfhCSYJYZbwBDlZ40xh1
NYnmZF1M17IRRsxIUrGwBXIEVQKBgQDM/kUTpa0DbKpkWR55WcZtCnQ3U5KgcqEU
AWCizbkUlyUlfSoQztYqXKrqUVHEfqoVanf1Pu5yHCgxCF5fZymDdRv53xSsUgtw
QgLNc8gJFQ5ZA41XwUNA+IMYEGab6kp1PhycaTnWGAs8NdUh70jTGB70j6UN/LVJ
lwcjiKuRXwKBgChn0UD1O99dXD1TvMB9x9+DCtLEW86u8GNdztTYlv57sAmaYSO7
XmeV+A/7Dt636FiC//SrFLpST20xvpEYFeFxkTmga65LmyOJd91Tbc+tjDv7Vi+B
3V977FxA7id5eAy45PdbqUzhsXn1B6YERVDKGbdG8HXFzv7NamrzfABJAoGAKjIE
ogCuVlAd2r4FadEy6OsH9QN84Q33XhjSfXB/Ml/SQ58582+/4cRlYgoPHLU96V6b
Bp5HkrF9DGq+kkC36NlIQuzKYpYYyKitzwCQIl51L5ltlKyxXURKJ7/ofxuA7BU2
6nM2dn1IgsJJ9sw8X0dNx+VxgimMX3N5ArV1K10CgYA1BBQr39x9vp+fj+MtFk6G
xvEcC/LVnGao9hH358Dv6qoNWHzEZJbmhqawOnJgquBiU/XBPiSeM33ts4qHyk4k
xU735PB7P6IEvAiS5RpVKW7BmwDd9rTaDARsKZmbflLUPuQHmS+s1BVwtsS+z5Fp
crb26NsrVwiTRVLnahHk9A==
-----END PRIVATE KEY-----""" # Substitua pela sua private_key real, mantendo as quebras de linha
client_email = "firebase-adminsdk-fbsvc@lgpd-ipem-mg-9f1a5.iam.gserviceaccount.com" # Substitua pelo seu client_email real
client_id = "111019883909349280563" # Substitua pelo seu client_id real
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40lgpd-ipem-mg-9f1a5.iam.gserviceaccount.com" # Substitua pela sua client_x509_cert_url real
# universe_domain = "googleapis.com" # Geralmente não é necessário para a inicialização padrão
